- role: "Conference reviewer"
  activity: "IEEE Conference on Computer Vision and Pattern Recognition (CVPR) 2019,<br>IEEE International Conference on Computer Vision (ICCV) 2019,<br>IEEE International Conference on Image Processing (ICIP) 2019,<br>British Machine Vision Conference (BMVC) 2019"
  brief: true
